### PR TITLE
editor: fix select sort

### LINKED ISSUE #568: The select component in the editor should sort the values only in the suggestions
When the "SelectWithSort" component is used for multiple values the list of the values are sorted which not reflect the order in the array. The sort operation should be effective only on the suggestion values.

In the follwing example the `created_year` if at the first place in the list, but as it is sorted it is displayed after `bibliothèque`.

image

### PR DESCRIPTION
**Pull request by Garfield-fr**
The "Select an option…" option remains displayed when values are selected. This option is used to reset the data.

* Keeps selected items in order.
* Improves the select menu by always displaying the menu item "Select an option…".
* Fixes missing translation.
* closes #568.

### CODE REVIEW

File: projects/rero/ng-core/src/lib/record/editor/type/custom-select/custom-select.component.ts [hunk 1]
```diff
@@ -140,6 +140,19 @@ export class CustomSelectFieldComponent extends FieldType implements OnDestroy,
    * @returns The selected values as string.
    */
   get selectedValuesAsString(): string {
+    if (Array.isArray(this.formControl.value)) {
+      // Keeps selected items in order
+      const data = [];
+      let optionSelected: SelectOption;
+      const selectedValue = this.formControl.value.filter((v: string) => v !== undefined);
+      selectedValue.forEach((val: string) => {
+        optionSelected = this.selectedOptions
```
Comment (zannkukai) [inline projects/rero/ng-core/src/lib/record/editor/type/custom-select/custom-select.component.ts:149]: I think in correct english it should be `selectedOption` (as `selectedValue` just line above)

**Review by zannkukai — APPROVED** [review]

File: projects/rero/ng-core/src/lib/record/editor/type/custom-select/custom-select.component.ts (hunk 1 above)
Comment (Garfield-fr) [reply projects/rero/ng-core/src/lib/record/editor/type/custom-select/custom-select.component.ts]: My English is not good and it shows in the code 🙈😂

File: projects/rero/ng-core/src/lib/record/editor/type/custom-select/custom-select.component.ts [hunk 2]
```diff
@@ -140,6 +140,19 @@ export class CustomSelectFieldComponent extends FieldType implements OnDestroy,
    * @returns The selected values as string.
    */
   get selectedValuesAsString(): string {
+    if (Array.isArray(this.formControl.value)) {
+      // Keeps selected items in order
+      const data = [];
+      let selectedOption: SelectOption;
+      const selectedValue = this.formControl.value.filter((v: string) => v !== undefined);
```
Comment (jma) [inline projects/rero/ng-core/src/lib/record/editor/type/custom-select/custom-select.component.ts:147]: This can be done in the foreach to avoid 2 iterations over the list.

**Review by jma — APPROVED** [review]

File: projects/rero/ng-core/src/lib/record/editor/type/custom-select/custom-select.component.ts (hunk 2 above)
Comment (Garfield-fr) [reply projects/rero/ng-core/src/lib/record/editor/type/custom-select/custom-select.component.ts:147]: I wanted to avoid an "if" in the foreach. So I filtered this list to eliminate the "undefined" ones. But if you want, I can put it in the loop?

**Review by PascalRepond — APPROVED** [review]

**Comment by PascalRepond** [comment]
Any way to make it work the same for the field "parent account" in account editor? To close https://github.com/rero/rero-ils/issues/2875
